# Generated by Django 5.1.6 on 2026-09-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0009_postev'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
