# Generated by Django 5.1.6 on 2026-09-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0011_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
