# Generated by Django 5.1.6 on 2026-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0012_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
